@Concert_Ticket_Management_System_HostAddress = http://localhost:5261



POST {{Concert_Ticket_Management_System_HostAddress}}/api/concerts
Content-Type: application/json

{
  "concertDate": "2025-06-15T19:00:00Z",
  "name": "EDC 2025",
  "description": "Let's rave.",
  "totalCapacity": 1,
  "ticketPricing": {
    "VIP": 150.0,
    "General": 50.0,
    "EarlyBird": 40.0,
    "Student": 30.0
  }
}
###

GET {{Concert_Ticket_Management_System_HostAddress}}/api/concerts
Content-Type: application/json

###
POST {{Concert_Ticket_Management_System_HostAddress}}/api/1/reserve-tickets
Content-Type: application/json

{
  "concertId": 1,
  "ticketType": "1",
  "quantity": 1
}

###

POST POST {{Concert_Ticket_Management_System_HostAddress}}/api/concerts
Content-Type: application/json

  {
       "concertDate": "2025-07-02T06:40:14.859Z",
       "name": "Concert Name",
       "description": "Concert Description",
       "totalCapacity": 100,
       "ticketPricing": {
           "VIP": 150.0,
           "General": 50.0
       }
   }
